myapp/urls.py
from django.conf.urls import url

from myapp import views

urlpatterns = [
    url(r'^$', views.home, name='index'),
    url(r'^home/$', views.home, name='home'),
    url(r'^cart/$', views.cart, name='cart'),
    url(r'^market/(\d+)/(\d+)/(\d+)/$', views.market, name='market'),
    url(r'^mine/$', views.mine, name='mine'),
    url(r'^registe/$', views.registe, name='registe'),  # 注册
    url(r'^checkaccount/$', views.checkaccount, name='checkaccount'),  # 账号验证
    url(r'^logout/$', views.logout, name='logout'),  # 退出
    url(r'^login/$', views.login, name='login'),  # 登录
    url(r'^addgoods/$', views.addgoods, name='addgoods'),  # 添加购物车
    url(r'^subgoods/$', views.subgoods, name='subgoods'),  # 购物车减操作
    url(r'^changecartstatus/$', views.changecartstatus, name='changecartstatus'),  # 修改选中状态
    url(r'changecartselect/$', views.changecartselect, name='changecartselect'),  # 全选/取消全选
    url(r'^generateorder/$',views.generateorder,name='generateorder'),  # 订单提交
    url(r'^order/(\d+)/$', views.order, name='order'),

]

myprojectaxf/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('myapp.urls',namespace='myapp')),
]

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <link rel="stylesheet" href="{% static 'base/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/swiper.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/base.css' %}">
    <title>
{#      标题#}
        {% block title %}
        {% endblock %}
    </title>
{#      CSS#}

    {% block extcss %}

    {% endblock %}



</head>


<body>
{# 头部#}
{% block header %}
    <header>爱鲜蜂</header>
{% endblock %}

{# 主体内容#}
<div class="hidescroll">
    <div id="content">
        {% block content %}

        {% endblock %}
    </div>
</div>

{# 尾部#}
{% block footer %}
    <footer>
        <a href="{% url 'myapp:home' %}" class="home">
            <dl>
                <dt> <span></span> </dt>
                <dd> 首页 </dd>
            </dl>
        </a>
c
        <a href="{% url 'myapp:market' 104749 0 0%}" class="market">
            <dl>
                <dt> <span></span> </dt>
                <dd> 闪购超市 </dd>
            </dl>
        </a>

        <a href="{% url 'myapp:cart' %}" class="cart">
            <dl>
                <dt> <span></span> </dt>
                <dd> 购物车 </dd>
            </dl>
        </a>

        <a href="{% url 'myapp:mine' %}" class="mine">
            <dl>
                <dt> <span></span> </dt>
                <dd> 我的 </dd>
            </dl>
        </a>
    </footer>
{% endblock %}

</body>



{# JS#}
<script src="{% static 'base/js/jquery.js' %}"></script>
<script src="{% static 'base/js/jquery.cookie.js' %}"></script>

<script src="{% static 'base/js/bootstrap.js' %}"></script>
<script src="{% static 'base/js/swiper.js' %}"></script>
<script src="{% static 'base/js/base.js' %}"></script>
{% block extjs %}
{% endblock %}

</html>